theme: jekyll-theme-cayman
title: "Great Ape Detection in Challenging Jungle Camera Trap Footage via Attention-Based Spatial and Temporal Feature Blending"
favicon: favicon.ico
github:
      is_project_page: false
